services:
  #  db:
  #    image: postgres:16-alpine
  #    container_name: meeting-room-booking-db
  #    ports:
  #      - "5432:5432"
  #    environment:
  #      - POSTGRES_DB=meeting_room_booking_db
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=password
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #    healthcheck:
  #      test: [ "CMD-SHELL", "pg_isready -U postgres -d meeting_room_booking_db" ]
  #      interval: 5s
  #      timeout: 5s
  #      retries: 5

  api:
    build:
      context: ./meeting-room-booking-api
      dockerfile: Dockerfile
    container_name: meeting-room-booking-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/meeting_room_booking_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_LIQUIBASE_ENABLED=true
      - PASETO_SECRET=viettel-meeting-room-booking-secret-key-2026
      - SMTP_HOST=${SMTP_HOST:-smtp.mailtrap.io}
      - SMTP_PORT=${SMTP_PORT:-2525}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
  #    depends_on:
  #      db:
  #        condition: service_healthy

  frontend:
    build:
      context: ./meeting-room-booking-fe
      dockerfile: Dockerfile
    container_name: meeting-room-booking-fe
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  postgres_data:
